### ISSUE TITLE
Issue with NAV 2018 CU6

### ISSUE THREAD

**Issue by nicoach** [wortho/NAVLoadTest#13]
Hello David,

When we run the project, we get the following error:

System.InvalidOperationException
  HResult=0x80131509
  Mensaje = Communication error was thrown:
System.ServiceModel.CommunicationException: **Could not parse the Json response**. The response was  ---> Newtonsoft.Json.JsonReaderException: Error reading JToken from JsonReader. Path '', line 0, position 0.
   en Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   en Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   en Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.<>c__DisplayClass9_0.<EndOpenSession>b__0()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.<>c__DisplayClass9_0.<EndOpenSession>b__0()
   en Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.ConvertExceptions[T](Func`1 action)
   en Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.EndOpenSession(IAsyncResult result)
   en Microsoft.Dynamics.Framework.UI.Client.ClientSession.<>c__DisplayClass37_0.<OpenSessionCallback>b__0()
   en Microsoft.Dynamics.Framework.UI.Client.ClientSession.HandleServiceExceptions(ClientSessionState errorState, Action action)
  Origen = Microsoft.Dynamics.Nav.UserSession
  Seguimiento de la pila:
   en Microsoft.Dynamics.Nav.UserSession.ClientSessionExtensions.AwaitReady(ClientSession clientSession, Action action, Func`2 readyCondition, Boolean allowClosed, Int32 maxDuration) en C:\Temp\NAVLoadTest-master\Microsoft.Dynamics.Nav.UserSession\ClientSessionExtensions.cs: línea 345
   en Microsoft.Dynamics.Nav.UserSession.ClientSessionExtensions.OpenSession(ClientSession clientSession, String uiCultureId) en C:\Temp\NAVLoadTest-master\Microsoft.Dynamics.Nav.UserSession\ClientSessionExtensions.cs: línea 48
   en Microsoft.Dynamics.Nav.UserSession.UserContext.OpenSession(String uiCultureId) en C:\Temp\NAVLoadTest-master\Microsoft.Dynamics.Nav.UserSession\UserContext.cs: línea 52
   en Microsoft.Dynamics.Nav.TestUtilities.UserContextManager.CreateSession(TestContext testContext) en C:\Temp\NAVLoadTest-master\Microsoft.Dynamics.Nav.TestUtilities\UserContextManager.cs: línea 71
   en Microsoft.Dynamics.Nav.TestUtilities.UserContextManager.GetUserContext(TestContext testContext) en C:\Temp\NAVLoadTest-master\Microsoft.Dynamics.Nav.TestUtilities\UserContextManager.cs: línea 100
   en Microsoft.Dynamics.Nav.TestUtilities.TestScenario.Run(UserContextManager manager, TestContext testContext, Action`1 action, String actionName) en C:\Temp\NAVLoadTest-master\Microsoft.Dynamics.Nav.TestUtilities\TestScenario.cs: línea 23
   en Microsoft.Dynamics.Nav.LoadTest.OrderProcessorScenarios.CreateAndPostSalesOrder() en C:\Temp\NAVLoadTest-master\Microsoft.Dynamics.Nav.LoadTest\OrderProcessorScenarios.cs: línea 133

Excepción interna 1:
CommunicationException: Could not parse the Json response. The response was 

Excepción interna 2:
JsonReaderException: Error reading JToken from JsonReader. Path '', line 0, position 0.

We are using the ODATA Service running in a NAV Server 2018 CU6 with the following URL: https://_ServerAddress_:7048/_NAVInstance_/ODatav4 
but when we run the url in a browser with the same credentials we get a json file.

Is it an issue of the project or a misconfiguration our?

Thank you very much in advance.

Best Regards

**Comment by wortho** [comment]
The error means that the response from the web client is not in a recognizable format. Possibly because the test client cannot reach the client service or there is an error during authentication. In this case it appears that you are using the wrong endpoint for the client service (cs). It should look like this: http://localhost:8080/NAV/WebClient/cs.

The NAV client service being used is the web client service (Web UI), not the NAV Web Services or OData endpoints.
