### ISSUE TITLE
Future of NAVLoadTest

### ISSUE THREAD

**Issue by AbsolutelyFreeWeb** [wortho/NAVLoadTest#14]
Hi, Thank you for development of this great tool. 
I'd like to ask if there are any additions / changes planned?
- Will you be supporting it for Business Central and coming versions? (cloud and on-prem)
- Will there be a change of tool since Visual Studio has indicated loadtest will be discontinued?

For now my project is for NAV2017. Enhancement request:
- I see that there is no scenario for opening a card from a list. It would have been handy. 
- Or open a card on a specific record directly.

**Comment by wortho** [comment]
Hi,

Thanks for the comments.

1. There is already a fork of the project for BC https://github.com/NAVPERF/BCONPREM-Sample
2. I don't yet know what the future holds for the tools. I am looking at alternatives like like JMeter.

I will add some examples of the suggested scenarios.

Regards,

David

**Comment by AbsolutelyFreeWeb** [comment]
Thank you. Here is my attempt of doing scenario one. I seem to be doing something wrong, because it is retrieving the same order every time. Function `Control` is renamed to `ControlByCaption`, since I also have a `ControlByName`:


```
                        //open order
                        ClientLogicalForm SalesOrderCard = null;
                        if (OrderWasAvailable)
                        {
                            ClientLogicalControl SalesOrderListNoField = rowControl.ControlByCaption(SalesOrderListOrderNo);
                            TestContext.WriteLine("Clicking the field for order no. {0}", SalesOrderListNoField.StringValue);
                            using (new TestTransaction(TestContext, "OpenOrder"))
                            {
                                SalesOrderCard = userContext.CatchForm(delegate
                                {
                                    userContext.InvokeInteraction(new InvokeActionInteraction(SalesOrderListNoField, SystemAction.View));
                                });
                            }
                            userContext.EnsurePage(SalesOrderPageId, SalesOrderCard);
                            TestContext.WriteLine("Opened Order card {0}", SalesOrderCard.ControlByCaption(SalesOrderCardOrderNo).StringValue);
```


Problem is when I'm running this in a loop, I get the first order (in the filtered order list) opened every time, even when I'm on other lines:

> User 1 Saved Order SYMSP444156
> Order list enumeration 1 => Saved 1 orders for this user
> Clicking the field for order no. SYMSP444156
> Opened Order card SYMSP444156
> Populating order line 1 of 1
> Populated order line 1 without lot
> User 1 Saved Order SYMSP444157
> Order list enumeration 2 => Saved 2 orders for this user
> Clicking the field for order no. SYMSP444157
> Opened Order card SYMSP444156
> Populating order line 1 of 1
> Populated order line 1 without lot
> User 1 Saved Order SYMSP444158
> Order list enumeration 3 => Saved 3 orders for this user
> Clicking the field for order no. SYMSP444158
> Opened Order card SYMSP444156
> Populating order line 1 of 1
> Populated order line 1 without lot 

Can you see something wrong with the code?

**Comment by wortho** [comment]
I can't see what is wrong here because I cannot see how you are selecting the SalesOrder.
 In order to scroll down the records in the list page you can look at the code in SelectRandomRecord.
Here is an example that uses it : [OpenSalesOrderCard](https://gist.github.com/wortho/e45db92d75d6cd5bd7bf7890cc86a003)

**Comment by AbsolutelyFreeWeb** [comment]
Thank you, Thank you! You just solved it for me by saying that ^^ I had the record and was forwarding it to the action, but the row wasn't actually selected. It started working after adding `SalesOrderListNoField.activate()`

**Comment by AbsolutelyFreeWeb** [comment]
Thank you for the new method, and thank you for solving it for me! It was just that, I wasn't selecting it, It started working after adding `SalesOrderListNoField.activate()` ^^
