### ISSUE TITLE
Line Count

### ISSUE THREAD

**Issue by DmitryNAV** [wortho/NAVLoadTest#4]
In test RunCreateAndPostSalesOrder exsist line
 // Add a random number of lines between 2 and 5
 int noOfLines = SafeRandom.GetRandomNext(2, 5);

When you try to change the range, such as SafeRandom.GetRandomNext(20, 25) get an error
-----------------
Test Name:	CreateAndPostSalesOrder
Test FullName:	Microsoft.Dynamics.Nav.LoadTest.OrderProcessorScenarios.CreateAndPostSalesOrder
Test Source:	c:\Users\XXX\Source\Repos\NAVLoadTest\Microsoft.Dynamics.Nav.LoadTest\OrderProcessorScenarios.cs : line 133
Test Outcome:	Failed
Test Duration:	0:01:28,8786043

Result Message:	
Test method Microsoft.Dynamics.Nav.LoadTest.OrderProcessorScenarios.CreateAndPostSalesOrder threw exception: 
System.ArgumentOutOfRangeException: Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
Имя параметра: index
Result StackTrace:	
в System.ThrowHelper.ThrowArgumentOutOfRangeException()
   в System.Collections.Generic.List`1.get_Item(Int32 index)
   в System.Collections.ObjectModel.Collection`1.get_Item(Int32 index)
   в Microsoft.Dynamics.Nav.LoadTest.OrderProcessorScenarios.AddSalesOrderLine(UserContext userContext, ClientLogicalForm newSalesOrderPage, Int32 line) в c:\Users\XXX\Source\Repos\NAVLoadTest\Microsoft.Dynamics.Nav.LoadTest\OrderProcessorScenarios.cs:строка 207
   в 
Microsoft.Dynamics.Nav.LoadTest.OrderProcessorScenarios.RunCreateAndPostSalesOrder(UserContext userContext) в c:\Users\XXX\Source\Repos\NAVLoadTest\Microsoft.Dynamics.Nav.LoadTest\OrderProcessorScenarios.cs:строка 167
   в Microsoft.Dynamics.Nav.TestUtilities.TestScenario.Run(UserContextManager manager, TestContext testContext, Action`1 action, String actionName) в c:\Users\XXX\Source\Repos\NAVLoadTest\Microsoft.Dynamics.Nav.TestUtilities\TestScenario.cs:строка 37
   в Microsoft.Dynamics.Nav.LoadTest.OrderProcessorScenarios.CreateAndPostSalesOrder() в c:\Users\XXX\Source\Repos\NAVLoadTest\Microsoft.Dynamics.Nav.LoadTest\OrderProcessorScenarios.cs:строка 134
-----------
This happens due to the fact that after the addition of a number of lines in Web client you need to call the view the next set of rows.
Is it possible to add a similar method?

We have just begun to use offered tool but now it seems to be extremely useful. Thank you!

**Comment by wortho** [comment]
Hi Dmitry. I will take a look at it. 
Cheers David

**Comment by wortho** [comment]
Hi Dmitry,

I have submitted a pull request with the fix for the line Count issue.
 See this commit:
https://github.com/wortho/NAVLoadTest/commit/662d7d2019ba1f0f3f78a35540a028565a440b70

Let me know if this yorks for you.

Regards,

David
